version: '3.8'

services:
  vcard-qr-generator:
    build: .
    ports:
      - "8080:80"
    container_name: vcard-qr-generator
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 